/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-11-04 16:46:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.adminTb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class membersTb_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/views/common/errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/adHeaderKKH.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("  \r\n");
      out.write("<!-- content-header -->\r\n");
      out.write("<div class=\"content-header\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row mb-2\">\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <h1 class=\"m-0 text-dark\">승인처리 게시판</h1>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("          <div class=\"col-sm-6\">\r\n");
      out.write("            <ol class=\"breadcrumb float-sm-right\">\r\n");
      out.write("              <li class=\"breadcrumb-item\"><a href=\"#\">Home</a></li>\r\n");
      out.write("              <li class=\"breadcrumb-item active\">승인처리</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("          </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("      </div><!-- /.container-fluid -->\r\n");
      out.write("    </div>\r\n");
      out.write("  <!-- //content-header -->\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" <!-- Main content -->\r\n");
      out.write("    <section class=\"content\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"card-title\">Responsive Hover Table</h3>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-tools\">\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                \r\n");
      out.write("              \r\n");
      out.write("                    <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- checkbox -->\r\n");
      out.write("                      <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          \r\n");
      out.write("                          <label class=\"form-check-label\"><input class=\"form-check-input\" type=\"checkbox\" checked />활성화 계정</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                          \r\n");
      out.write("                          <label class=\"form-check-label\"><input class=\"form-check-input\" type=\"checkbox\" checked />비활성화 계정</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                 \r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>전체</option>\r\n");
      out.write("                          <option>이름</option>\r\n");
      out.write("                          <option>아이디</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                  <div class=\"input-group input-group-sm\" style=\"width: 150px;\">\r\n");
      out.write("                    <input type=\"text\" name=\"table_search\" class=\"form-control float-right\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("                    <div class=\"input-group-append\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-default\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-header -->\r\n");
      out.write("              <div class=\"card-body table-responsive p-0\">\r\n");
      out.write("                <table class=\"table table-hover text-nowrap text-center\">\r\n");
      out.write("                  <thead>\r\n");
      out.write("                    <tr class=\"text-center\" >\r\n");
      out.write("                      <th>회원번호</th>\r\n");
      out.write("                      <th>이름</th>\r\n");
      out.write("                      <th>아이디</th>\r\n");
      out.write("                      <th>등급</th>\r\n");
      out.write("                      <th>부서</th>\r\n");
      out.write("                      <th>직급</th>\r\n");
      out.write("                      <th>상태</th>                      \r\n");
      out.write("                      <th>활성화/비활성화</th>\r\n");
      out.write("                      <th><label class=\"mch\"><input type=\"checkbox\"/></label></th>\r\n");
      out.write("                      <th>가입처리</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </thead>\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                  \r\n");
      out.write("                    <tr class=\"text-center\" style=\"vertical-align:middle;\">\r\n");
      out.write("                      <td>183</td>\r\n");
      out.write("                      <td>John Doe</td>\r\n");
      out.write("                      <td><a href=\"/views/adminTb/adMemInfo.jsp\">dsfsdfsdf</a></td>\r\n");
      out.write("                      \r\n");
      out.write("                       <td>\r\n");
      out.write("       \r\n");
      out.write("                     <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>등급</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("         \r\n");
      out.write("                      \r\n");
      out.write("                      </td>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <td>\r\n");
      out.write("       \r\n");
      out.write("                     <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>부서</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("         \r\n");
      out.write("                      \r\n");
      out.write("                      </td>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <td>\r\n");
      out.write("                      \r\n");
      out.write("                       <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>직급</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("         \r\n");
      out.write("                      \r\n");
      out.write("                      </td>\r\n");
      out.write("                      <td>\r\n");
      out.write("                      \r\n");
      out.write("                       <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>상태</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("         \r\n");
      out.write("                      \r\n");
      out.write("                      </td>\r\n");
      out.write("                      <td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <div class=\"col-sm-10\">\r\n");
      out.write("                      <!-- select -->\r\n");
      out.write("                      <div class=\"form-group float-right selright\">\r\n");
      out.write("                        <select class=\"form-control\">\r\n");
      out.write("                          <option>활성화유무</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("         \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("                      <td><label class=\"mch\"><input type=\"checkbox\"/></label></td>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                      <td><button type=\"button\" class=\"btn btn-primary col-10\">승인</button></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("          \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.card-body -->\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"btfloat\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary col-1\">삭제</button>\r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("     \t\t<button type=\"button\" class=\"btn  btn-primary col-1\">승인</button>\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("              <button type=\"button\" class=\"btn  btn-primary col-1\">숨김</button>\r\n");
      out.write("               </div>\r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("                <div class=\"card-footer clearfix\" style=\"margin:0 auto;\">\r\n");
      out.write("                <ul class=\"pagination pagination-sm m-0\" >\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">&laquo;</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.card -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        </section>\r\n");
      out.write("   </div><!-- //Content Wrapper. Contains page content -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/adFooterKKH.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
