/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-11-04 08:26:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.register;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <title>일조 그룹웨어 회원가입</title>\r\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/plugins/fontawesome-free/css/all.min.css\">\r\n");
      out.write("  <!-- Ionicons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("  <!-- icheck bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/plugins/icheck-bootstrap/icheck-bootstrap.min.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/dist/css/adminlte.css\">\r\n");
      out.write("  <!-- Google Font: Source Sans Pro -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition register-page\">\r\n");
      out.write("<div class=\"register-box\">\r\n");
      out.write("  <div class=\"register-logo\">\r\n");
      out.write("     <img src=\"/resources/images/biglogo.png\" />\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    <div class=\"card-body register-card-body\">\r\n");
      out.write("      <p class=\"login-box-msg\">Register a new membership</p>\r\n");
      out.write("\r\n");
      out.write("      <form action=\"/register/register\" method=\"post\" >\r\n");
      out.write("      <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" placeholder=\"아이디\"  id=\"user_id\" name=\"user_id\"> \r\n");
      out.write("          <div class=\"check_font\" id=\"id_check\"></div>  \r\n");
      out.write("          <div>       \r\n");
      out.write("            </div>\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-envelope\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"margin:5px 0px;\"> @일조.kr </div> \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"password\" class=\"form-control\" placeholder=\"비밀번호\" id=\"user_pw\" name=\"user_pw\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"password\" class=\"form-control\" id=\"user_pw2\" name=\"user_pw2\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-lock\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"user_name\" placeholder=\"이름\" >\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-user\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"identify\" placeholder=\"주민등록번호\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"far fa-address-card\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input  type=\"text\"  class=\"form-control\" name=\"cellphone_no\" placeholder=\"핸드폰번호\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-mobile-alt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("         <div class=\"input-group mb-3\">\r\n");
      out.write("          <input  type=\"text\"  id=\"sample6_postcode\" class=\"form-control\" name=\"user_addr\" placeholder=\"우편번호\">\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-map-marker-alt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-4\">\r\n");
      out.write("           <button type=\"button\" onclick=\"sample6_execDaumPostcode()\" class=\"btn btn-primary btn-block\">주소검색</button>\r\n");
      out.write("           </div>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input  type=\"text\" id=\"sample6_address\"  class=\"form-control\" name=\"user_addr2\" placeholder=\"주소\"> \r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-map-marker-alt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>          \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("          <input  type=\"text\" id=\"sample6_address2\" class=\"form-control\" name=\"user_addr3\" placeholder=\"상세주소\">  \r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"fas fa-map-marker-alt\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"input-group mb-3\">\r\n");
      out.write("         <div class=\"text-center\">\r\n");
      out.write("          프로필에 보여질 사진과 문구를 적어주세요.\r\n");
      out.write("                  <img class=\"profile-user-img img-fluid img-circle\" src=\"/resources/dist/img/user4-128x128.jpg\" alt=\"사용자 프로필 사진\">\r\n");
      out.write("            </div>\r\n");
      out.write("              <input  type=\"text\"  class=\"form-control\" name=\"user_notice\" placeholder=\"20자 이내로 적어주세요\">\r\n");
      out.write("                   <div class=\"input-group-append\">\r\n");
      out.write("            <div class=\"input-group-text\">\r\n");
      out.write("              <span class=\"far fa-file-alt\"></span>\r\n");
      out.write("          </div> \r\n");
      out.write("                </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-8\">\r\n");
      out.write("            <div class=\"icheck-primary\">\r\n");
      out.write("              <input type=\"checkbox\" id=\"agreeTerms\" name=\"terms\" value=\"agree\">\r\n");
      out.write("              <label for=\"agreeTerms\">\r\n");
      out.write("               개인정보 이용약관에 <br><a href=\"#\">동의합니다</a>\r\n");
      out.write("              </label>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("          <div class=\"col-4\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-block\">가입하기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("      <a href=\"login.html\" class=\"text-center\">I already have a membership</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.form-box -->\r\n");
      out.write("  </div><!-- /.card -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- /.register-box -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function sample6_execDaumPostcode() {\r\n");
      out.write("            new daum.Postcode({\r\n");
      out.write("                oncomplete: function (data) {\r\n");
      out.write("                    // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                    // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                    // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                    var fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("                    var extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                    // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                        fullAddr = data.roadAddress;\r\n");
      out.write("\r\n");
      out.write("                    } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                        fullAddr = data.jibunAddress;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("                    if (data.userSelectedType === 'R') {\r\n");
      out.write("                        //법정동명이 있을 경우 추가한다.\r\n");
      out.write("                        if (data.bname !== '') {\r\n");
      out.write("                            extraAddr += data.bname;\r\n");
      out.write("                        }\r\n");
      out.write("                        // 건물명이 있을 경우 추가한다.\r\n");
      out.write("                        if (data.buildingName !== '') {\r\n");
      out.write("                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                        }\r\n");
      out.write("                        // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("                        fullAddr += (extraAddr !== '' ? ' (' + extraAddr + ')' : '');\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                    document.getElementById('sample6_address').value = fullAddr;\r\n");
      out.write("\r\n");
      out.write("                    // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                    document.getElementById('sample6_address2').focus();\r\n");
      out.write("                }\r\n");
      out.write("            }).open();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap 4 -->\r\n");
      out.write("<script src=\"/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- AdminLTE App -->\r\n");
      out.write("<script src=\"/resources/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
